name: On Issue Closed
on:
  issues:
    types: [closed]

jobs:
  issue-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Extract Jira issue key
        id: extract_key
        run: |
          echo "::set-output name=issue_key::${{ github.event.issue.title }} | grep -oP '\[\K[^]]+')"

      - name: Close Task
        run: |
          curl \
           -D- \
           -u '${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_PASSWD }}' \
           -X POST \
           -H "Content-Type: application/json" \
           --data '{"transition":{"id":"31"}}'
           https://${{ secrets.JIRA_URL }}/rest/api/2/issue/${{ steps.extract_key.outputs.issue_key }}/transitions
