# This is a basic workflow to help you get started with Actions

name: Create JIRA Task as Issue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 0 * * *" # At 00:00 Everydays.

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jira pygithub  

    - name: Get data from Jira and create issue
      env: 
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_PASSWD: ${{ secrets.JIRA_PASSWD }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        python jira_task.py
