name: On Issue Closed
on:
  issues:
    types: [closed, labeled, unlabeled]

jobs:
  issue-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Extract Jira issue key
        id: extract_key
        run: |
          echo "::set-output name=issue_key::${{ github.event.issue.title }} | grep -oP '\[\K[^]]+'"

      - name: Task Action
        run: |
          if [[ "${{ github.event.action }}" == "closed" ]]; then
            $id="31"
          elif [[ "${{ github.event.action }}" == "labeled" && "${{ github.event.label.name }}" == "on-going" ]]; then
            $id="21"
          fi
          
          curl --request POST  \ 
          --url 'https://${{ secrets.JIRA_URL }}/rest/api/2/issue/REP-181/transitions'   \
          --user '${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_PASSWD }}'   \
          --header 'Accept: application/json'   \
          --header 'Content-Type: application/json'   \
          --data '{"transition": {"id": $id}}'
