name: On Issue Closed
on:
  issues:
    types: [closed, labeled, unlabeled]

jobs:
  issue-closed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Extract Jira issue key
        id: extract_key
        run: |
          echo "issue_key=$(echo ${{ github.event.issue.title }} | grep -oP '\[\K[^]]+')" >> $GITHUB_OUTPUT
          
      - name: Check Status
        id: issue_status
        run: |
          if [[ "${{ github.event.action }}" == "closed" ]]; then
            echo "id='31'" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.action }}" == "labeled" && "${{ github.event.label.name }}" == "on-going" ]]; then
            echo "id='21'" >> $GITHUB_OUTPUT
          fi
          
      - name: Check Status
        run: |
          curl --request POST  \ 
          --url 'https://${{ secrets.JIRA_URL }}/rest/api/2/issue/${{ steps.extract_key.outputs.issue_key }}/transitions'   \
          --user '${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_PASSWD }}'   \
          --header 'Accept: application/json'   \
          --header 'Content-Type: application/json'   \
          --data '{"transition": {"id": ${{ steps.issue_status.outputs.id }}}}'
